### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by sb07** [liabru/gears-d3-js#1]
Hey you adapted work from a GNU GPL and put an MIT license on it. This isnt compatible as i understand it:
http://stackoverflow.com/questions/3902754/mit-vs-gpl-license

Can you elaborate?

**Comment by liabru** [comment]
Thank you for raising this. When I released this code in early 2014, there was no visible GPL license on the original work [[1]](https://web-beta.archive.org/web/20141017164435/https://bl.ocks.org/mbostock/1353700) or the website [[2]](https://web-beta.archive.org/web/20141018182246/http://bl.ocks.org:80/) like there is now. Given the purpose of the [blocks](http://bl.ocks.org/) website is to give example code for people learning [d3.js](https://github.com/d3/d3), I thought it to be given under public domain (I realise now this may have been a mistake).

From my memory and looking at older versions of the page and repository, it wasn't marked as GPL like it is today and this seems to be a retrospective addition (as of Feb 9, 2016 [[4]](https://gist.github.com/mbostock/1353700/27a5e7be5770fcdfcacdac48103193ff72ffc3c4)). I believe the author may be within his rights to do this if there was no original license (an odd situation given it was clearly provided as example code).

I'm not entirely sure what the resolution is here. I could probably change the license to GPL, but personally I am not happy with that license.

@mbostock can you advise? Is it ok given the circumstances, for you to allow this instance to be under MIT? Or must I change to GPL? Thanks.

1. https://web-beta.archive.org/web/20141017164435/https://bl.ocks.org/mbostock/1353700
2. https://web-beta.archive.org/web/20141018182246/http://bl.ocks.org:80/
3. https://gist.github.com/mbostock/1353700/revisions?page=1
4. https://gist.github.com/mbostock/1353700/27a5e7be5770fcdfcacdac48103193ff72ffc3c4

**Comment by mbostock** [comment]
bl.ocks.org is a live viewer on top of GitHub Gist. It can be used by anyone: any GitHub Gist with an index.html or README.md can appear on bl.ocks.org. Yes, it is used by me and others to share code examples for D3—as well as for graphics, toys, and experiments that I don’t really consider examples—but you should not assume anything about the licensing of the code simply by its existence on bl.ocks.org (or GitHub). And in general you should not assume you can reuse code that does not have a license obviously attached to it.

Historically, the reason my examples did not have a license is that I could not find a suitable license for examples. The open-source licenses we commonly use are intended for libraries and other reusable software. Examples are fundamentally different: they serve to teach (an API, a language, a technique, *etc.*) not to be reused verbatim. I wanted the examples to be used primarily for learning and as starting points for creative work, not to be repackaged in bulk (say as chart templates in commercial products). The working policy, if you asked, was in the spirit of the [O’Reilly policy on re-use of code examples from books](http://archive.oreilly.com/pub/a/oreilly/ask_tim/2001/codepolicy.html).

On a practical level however, this wasn’t a viable strategy. I am not a lawyer and did not have the resources or knowledge to formalize acceptable use. So I left it in a gray area and pointed people to the O’Reilly policy if they asked. In February 2016 I decided a simpler, more explicit approach that would be consistent with my aims would be to license my examples under the GPL. The GPL still isn’t a perfect fit, however, because it is a little bit too strict. If someone uses my example code in a “transformative” way—they are not just repackaging it verbatim for commercial use—then I do generally wish to enable that usage. But again from a practical perspective I do not think it is possible to formalize this distinction, so the GPL serves as a readily-available compromise.

I’ve looked at your code, and this library far exceeds the bar for transformative use of my code. If you want an explicit exemption to relicense my [bl.ocks.org/1353700](https://bl.ocks.org/mbostock/1353700) under ISC for use this in library, consider it granted!

**Comment by liabru** [comment]
My apologies, I appreciate you taking the time here to clear this up. Thanks!
